# Project: Project3
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../12/main.o ../12/board.o
LINKOBJ  = ../12/main.o ../12/board.o
LIBS     = -L"C:/Users/okjh0/Dev-c++/Dev-Cpp/MinGW64/lib" -L"C:/Users/okjh0/Dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/okjh0/Dev-c++/Dev-Cpp/MinGW64/include" -I"C:/Users/okjh0/Dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/okjh0/Dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/okjh0/Dev-c++/Dev-Cpp/MinGW64/include" -I"C:/Users/okjh0/Dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/okjh0/Dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/okjh0/Dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project3.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

../12/main.o: ../12/main.c
	$(CC) -c ../12/main.c -o ../12/main.o $(CFLAGS)

../12/board.o: ../12/board.c
	$(CC) -c ../12/board.c -o ../12/board.o $(CFLAGS)
